# Generated by Django 4.1.2 on 2022-10-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=5)),
                ('sigungu', models.CharField(max_length=5)),
                ('eupmyeondong', models.CharField(max_length=5)),
                ('note', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EupmyeondongPublicOffical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=5)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SigunguPublicOffical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=5)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ViallgeLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('tel', models.CharField(max_length=15)),
                ('note', models.CharField(max_length=5)),
            ],
        ),
    ]
