# Generated by Django 4.1.2 on 2022-10-13 12:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UDB_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EupmyeondongPublicOffical',
        ),
        migrations.DeleteModel(
            name='SigunguPublicOffical',
        ),
        migrations.DeleteModel(
            name='ViallgeLawyer',
        ),
        migrations.RemoveField(
            model_name='commissionedarea',
            name='eupmyeondong',
        ),
        migrations.RemoveField(
            model_name='commissionedarea',
            name='note',
        ),
        migrations.RemoveField(
            model_name='commissionedarea',
            name='sido',
        ),
        migrations.RemoveField(
            model_name='commissionedarea',
            name='sigungu',
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='city',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='con',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='cop',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='cot',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='county',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='emd',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='eon',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='eop',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='eot',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='ln',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarea',
            name='lt',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
